apiVersion: v1

kind: Service
metadata:
  name: logstash-pravega
spec:
  ports:
  - port: 514
    protocol: TCP
    targetPort: tcp
  selector:
    app: nautilus-demo
    component: logstash-pravega
    release: {{ .Release.Name }}
  type: LoadBalancer
